spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#     url: jdbc:mysql://192.168.149.10:3306/springcloud_shell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/springcloud_shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.43.13
    port: 5672
    password: guest
    username: guest
  redis:
    host: localhost
    port: 6379
env:
  dev
girl:
  age: 18
