spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: jiangchengyu998
    password: jiangchengyu998
    url: jdbc:mysql://47.105.169.153:3306/springcloud_shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 47.105.169.153
    port: 5672
    password: guest
    username: guest
env:
  test
