spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: jiangchengyu998
    password: jiangchengyu998
    url: jdbc:mysql://192.168.149.10:3306/springcloud_shell?characterEncoding=utf-8&useSSL=false
    # url: jdbc:mysql://192.168.0.6:3306/springcloud_shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 47.105.169.153
    port: 5672
    password: guest
    username: guest
  redis:
    host: 47.105.169.153
    port: 3308
env:
  dev
girl:
  age: 18
