spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#     url: jdbc:mysql://192.168.149.10:3306/springcloud_shell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/springcloud_shell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  redis:
    port: 6379
    host: localhost
  jpa:
    show-sql: true
